system:
  id: "trust-monitoring-system"
  update_interval: 30
  trust_thresholds:
    critical: 0.2
    warning: 0.5
    normal: 0.8

data_sources:
  - name: "prometheus"
    type: "prometheus"
    endpoint: "http://localhost:9090"
    enabled: true
  - name: "elasticsearch"
    type: "elasticsearch"
    endpoint: "http://localhost:9200"
    enabled: true
  - name: "jaeger"
    type: "jaeger"
    endpoint: "http://localhost:14268"
    enabled: true

notification_channels:
  - channel_id: "email-alerts"
    type: "email"
    endpoint: "alerts@company.com"
    enabled: true
  - channel_id: "slack-alerts"
    type: "slack"
    endpoint: "https://hooks.slack.com/services/..."
    enabled: true
  - channel_id: "pagerduty"
    type: "pagerduty"
    endpoint: "https://events.pagerduty.com/v2/enqueue"
    enabled: true

escalation_policies:
  - policy_id: "critical-trust-score"
    name: "Critical Trust Score Response"
    conditions:
      - "trust_score < 0.2"
    actions:
      - "isolate_component"
      - "send_alert"
      - "escalate_to_security_team"
    priority: 1
  
  - policy_id: "warning-trust-score"
    name: "Warning Trust Score Response"
    conditions:
      - "trust_score < 0.5"
    actions:
      - "send_alert"
      - "increase_monitoring"
    priority: 2

response_policies:
  - policy_id: "trust-score-critical"
    name: "Critical Trust Score Response"
    conditions:
      - type: "trust_score"
        metric: "trust_score"
        operator: "less_than"
        threshold: 0.2
    actions:
      - action_id: "isolate-component"
        type: "isolate_component"
        target_components: ["affected_component"]
        timeout: 30
        retry_count: 3
      - action_id: "send-alert"
        type: "send_notification"
        target_components: ["security_team"]
        timeout: 10
        retry_count: 1
    priority: 1
    enabled: true

recovery_plans:
  - plan_id: "service-recovery"
    name: "Service Recovery Plan"
    target_components: ["microservice", "database", "cache"]
    recovery_steps:
      - step_id: "restart-service"
        step_name: "Restart Service"
        action_type: "restart_service"
        timeout: 60
        retry_count: 3
      - step_id: "verify-health"
        step_name: "Verify Health"
        action_type: "health_check"
        timeout: 30
        retry_count: 5
    success_criteria:
      - criterion_id: "service-healthy"
        metric_name: "health_score"
        operator: "greater_than"
        threshold: 0.8
        description: "Service health score above 0.8"
    timeout: 300
